eon_customs/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include("home.urls")),
    path('projects/', include("projects.urls")),
    path('checkout/', include("checkout.urls")),
    path('profile/', include("profiles.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name="home"),
]

projects/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.all_projects, name="projects"),
    path('view/<id>', views.project_details, name="project_details"),
    path('request', views.project_request, name="project_request"),
    path('add', views.add_project, name="add_project"),
    path('edit/<id>', views.edit_project, name="edit_project"),
    path('delete/<id>', views.delete_project, name="delete_project"),
    path('delete/<projectId>/<commentId>',
         views.delete_comment, name="delete_comment"),
]

projects/models.py
from django.db import models
from django.conf import settings


from django.db.models.signals import post_save
from django.dispatch import receiver

from django.core.mail import send_mail

from django.core.exceptions import ObjectDoesNotExist

# each project can be any of these categories


class Category(models.Model):
    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    examplePrice_shortterm = models.DecimalField(
        max_digits=6, decimal_places=2)
    examplePrice_midterm = models.DecimalField(max_digits=6, decimal_places=2)
    examplePrice_longterm = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.friendly_name

# each project in the site


class Project(models.Model):
    category = models.ForeignKey('Category', on_delete=models.PROTECT)

    name = models.CharField(max_length=254)
    description = models.TextField()

    # price listing for the project
    price = models.DecimalField(max_digits=6, decimal_places=2)
    expectedLength = models.DurationField(
        verbose_name="Expected Development Time")
    startDate = models.DateField(
        null=True, blank=True, verbose_name="Start Date")

    approved = models.BooleanField(default=False)

    image = models.ImageField(null=True, blank=True,
                              upload_to="media/submitted")

    suggester = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name

# superclass to Comments and Updates, a notification for a project


class Message(models.Model):
    item = models.ForeignKey('Project', null=True,
                             blank=True, on_delete=models.SET_NULL)
    header = models.CharField(max_length=255)
    body = models.TextField(null=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_on']
        abstract = True


class Comment(Message):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'Comment "{self.body}" by {self.owner}'


class Update(Message):  # associated with account, account views all they have funded + able to see updates specifically for those ones in a special view
    def __str__(self):
        return f'{self.item} update {self.created_on}'

    # function to send the email to the user if they have it enabled
    def sendEmail(self):
        suggester = self.item.suggester
        # if the item doesnt have a related commission, funder doesnt exist so set to None
        try:
            funder = self.item.commission.user
        except Exception as e:
            funder = None
        body = self.body + \
            "\n\nIf you have any issue, please respond to this email and we will get back to you (not really this is a fake email)"
        if suggester == funder:  # if suggester and funder are the same person, dont send two emails, just the one that makes sense
            if suggester.userprofile.email_updates:
                send_mail(
                    f'Hi {suggester} : New update for suggested and funded project {self.item} - {self.header}',
                    body,
                    None,
                    [suggester.email, ],
                    fail_silently=False
                )
        else:  # else check each setting individually and send seperate emails
            if suggester.userprofile.email_updates:
                print("hi")
                send_mail(
                    f'Hi {suggester} : New update for suggested idea {self.item} - {self.header}',
                    body,
                    None,
                    [suggester.email],
                    fail_silently=False
                )
            if funder and funder.userprofile.email_updates:  # only send to funder if they exist
                send_mail(
                    f'Hi {funder} : New update for funded project {self.item} - {self.header}',
                    body,
                    None,
                    [funder.email],
                    fail_silently=False
                )


@receiver(post_save, sender=Update)
def sendUpdate(sender, instance, created, **kwargs):
    if created:
        instance.sendEmail()

projects/forms.py
from .models import Comment, Project, Update
from django import forms
from datetime import datetime
from datetime import timedelta


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('header', 'body')
        labels = {
            'header': "Title",
            'body': "Comment"
        }


class UpdateForm(forms.ModelForm):
    class Meta:
        model = Update
        fields = ('header', 'body')
        labels = {
            'header': "Title",
            'body': "Comment"
        }


class ProjectSuggestForm(forms.ModelForm):
    scale = forms.ChoiceField(label="Project Scale", choices=((None, 'Select Timescale'), (
        "shortterm", '1 week'), ("mediumterm", '1 month'), ("longterm", '3 months')))

    priceEstimate = forms.Field(
        required=False, disabled=True, label="Estimated Price to fund")

    # when saved calc specific details from form entry
    def save(self, costDistribution, suggester, commit=True):
        instance = super(ProjectSuggestForm, self).save(commit=False)
        # convert scale given to a timedelta object
        scale = self.cleaned_data["scale"]
        print(scale)
        if (scale == "shortterm"):
            instance.expectedLength = timedelta(days=2*7)  # 2 weeks
        elif (scale == "mediumterm"):
            instance.expectedLength = timedelta(days=4*7)  # 4 weeks
        elif (scale == "longterm"):
            instance.expectedLength = timedelta(days=12*7)  # 12 weeks
        # ensure approved is set to false
        instance.approved = False
        # calculate price from scale + category in the costDistribution table
        instance.price = costDistribution[str(
            scale) + str(instance.category.id)]
        instance.suggester = suggester

        if commit:
            instance.save()
        return instance

    class Meta:
        model = Project
        fields = ('name', 'category', 'description', 'image')
        labels = {'name': "Project Title"}
        widgets = {
            'name': forms.TextInput(
                attrs={'placeholder': 'Enter a succint name for your suggestion'}),
            'description': forms.Textarea(
                attrs={'placeholder': 'Describe in as much detail as possible what you want from the project'}),
        }

    field_order = ['name', 'category', 'scale',
                   'priceEstimate', 'description', 'image']


class DateInput(forms.DateInput):
    input_type = 'date'


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        exclude = []
        widgets = {
            'startDate': DateInput(),
            'endDate': DateInput(),
        }

projects/templates/projects/add_project.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <hr>
                <h2 class="logo-font mb-4">Item Management</h2>
                <h5 class="text-muted">Add a Project</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <form method="POST" action="{% url 'add_project' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% load crispy_forms_tags %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'projects' %}">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit">Add Project!</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

projects/templates/projects/edit_project.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <hr>
                <h2 class="logo-font mb-4">Item Management</h2>
                <h5 class="text-muted">Edit Project</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <p>
                    If approving a project, please make sure length is appropriate for the task and please dont supply a startdate
                </p>
                <form method="POST" action="{% url 'edit_project' project.id %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% load crispy_forms_tags %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'projects' %}">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit">Submit edit!</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

projects/templates/projects/project_details.html
{% extends "base.html" %}
{% load static %} 


{% block content %} 
<div class="overlay"></div>
<div class="container-fluid">
    <div class="row">
        <div class="col-10 offset-1 ">
            <div class="row">
                <div class="col text-center mt-3">
                    <h2 class="logo-font">{{ project.name }}</h2>
                    <hr class="w-50 mb-1">
                </div>
            </div>
            <div class="row rounded bg-white">
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="image-container my-5">
                        {% if project.image %}
                            <a href="{{ project.image.url }}" target="_blank">
                                <img class="card-img-top img-fluid border border-dark" src="{{ project.image.url }}" alt="{{ project.name }}">
                            </a>
                            {% else %}
                            <a href="">
                                <img class="card-img-top img-fluid border border-dark" src="{{ MEDIA_URL }}/noimage.png" alt="{{ project.name }}">
                            </a>
                        {% endif %}
                    </div>
                </div>
                <div class="col-12 col-md-6 {% if request.user.is_superuser %}col-lg-4{%else%}col-lg-8{%endif%}">
                    <div class="project-details-container mb-5 mt-md-5">
                        {% if not project.approved and request.user.is_superuser %}
                            <div class="text-center">
                                <a class="btn btn-danger float-center" href="{% url 'edit_project' project.id %}" role="button">Project not yet approved - edit now?</a>
                            </div>
                        {%endif%}
                        <p class="lead mb-0 text-left">
                        {% if project.startDate %} 
                            {{project.startDate}} - {{projectEndDate}}
                        {% else %}
                            {% load timedelta_filter %}
                            Project expected to take {{project.expectedLength|timedelta:"{days_total} days"}}
                        {% endif %}
                        </p>
                        <p class="lead mb-0 text-left font-weight-bold">Funding cost: £{{ project.price }} {% if project.commission %}- <i>funded</i>{%endif%}</p>
                        {% if project.category %}
                            <p class="small mt-1 mb-0">
                                <a class="text-muted" href="{% url 'projects' %}?category={{ project.category.name }}">
                                    <i class="fas fa-tag mr-1"></i>{{ project.category.friendly_name }}
                                </a>
                            </p>
                        {% endif %}
                        {%if request.user == project.suggester or request.user == project.commission.user or request.user.is_superuser%}
                            <button type="button" class="btn btn-secondary btn" data-toggle="modal" data-target="#modalProject">
                                View Project Updates ({{project.update_set.all|length}})
                            </button>
                        {%endif%}
                        {% if request.user.is_superuser %}
                            <small class="ml-3">
                                <a href="{% url 'edit_project' project.id %}">Edit</a> | 
                                <a class="text-danger" href="{% url 'delete_project' project.id %}">Delete</a>
                            </small>
                        {% endif %}
                        <p class="mt-3" style="white-space: pre-wrap">{{ project.description }}</p>

                        {% if project.suggester %}
                            <p class="mt-3"><i>initially suggested by <strong>{{project.suggester}}</strong></i></p>    
                        {%endif%}
                    
                        {% if project.commission %} 
                            <p class="mt-3"><i>funded by <strong>{{project.commission.user}}</strong></i></p>               
                        {% elif request.user.is_authenticated %}
                            <div class="text-center">
                                <a class="btn btn-primary float-center" href="{%url 'checkout' project.id%}" role="button">Fund this project for £{{project.price}}!</a>
                            </div>
                        {% else %}
                            <div class="text-center">
                                <a class="btn btn-info float-center" href="#" role="button">Please log in if you want to fund this item!</a>
                            </div>
                        {%endif%}
                    </div>
                </div>
                {% if request.user.is_superuser %}
                <div class="col-12 col-lg-4">
                    <div class="text-center mt-3">
                        <h2 class="logo-font">Update</h2>
                        <p>
                            Send an update that notifys the original project suggester {%if project.commission%} and funder {%endif%} on the state of the process
                        </p>
                    </div>
                    <div class="mb-5">
                        {% load crispy_forms_tags %}
                            <div class="card-body pb-0">
                                <form method="post" style="margin-top: 1.3em;">
                                    {{ update_form | crispy }}
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary btn-lg" name="updateForm">Submit</button>
                                    <button type="button" class="btn btn-secondary btn-lg" data-toggle="modal" data-target="#modalProject">
                                        View Previous Project Updates ({{project.update_set.all|length}})
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                    
                {%endif%}
            </div>
            <hr>
            <div class="row">
                <div class="col comments" style="padding: 10px;">
                    {%for comment in comments%}
                        <div class="card border-0 text-dark">
                            <b>{{comment.owner}} - {{comment.header}}</b>
                            <div class="card-body pb-0">
                                <p class="mb-0" style="white-space: pre-wrap">{{comment.body}}</p>
                            </div>
                            <div class="card-footer pt-0 bnorder-0 text-left">
                                <i>made on {{comment.created_on}}</i>
                            </div>
                            {% if request.user.is_superuser %}
                                <small class="ml-3">
                                    <a href="{% url 'delete_comment' project.id comment.id %}">Delete</a>
                                </small>
                            {% endif %}
                        </div>
                        <hr>
                    {%endfor%}
                    {% if request.user.is_authenticated %}
                        <div class="card h-10 border-0">
                            <h5 class="card-title">
                                Leave a Comment!
                            </h5>
                            {% load crispy_forms_tags %}
                            <div class="card-body pb-0">
                                <form method="post" style="margin-top: 1.3em;">
                                    {{ comment_form | crispy }}
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary  btn-lg" name="commentForm">Submit</button>
                                </form>
                            </div>
                        </div>
                    {% endif %}
                </div>
                <hr>
            </div>
        </div>
        
    </div>

</div>

{% if request.user.is_superuser or request.user == project.suggester or request.user == project.commission.user %}
<div class="modal fade" id="modalProject" tabindex="-1" role="dialog"
aria-labelledby="modalProjectLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalProjectLabel">Updates for <strong>{{project}}</strong></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {%if project.update_set.all|length == 0%} 
                No Updates For this project yet! stay tuned
                {%else%}
                {% for update in project.update_set.all reversed %}
                <div class="card border-0">
                    <div class="card-body border-0">
                        <p class="mb-0 font-weight-bold">{{update.header}}</p>
                    </div>
                    <div class="card-footer bg-white pt-0 bnorder-0 text-left">
                        <div class="row">
                            <div class="col">
                                <p>{{update.created_on}}</p>
                                <p style="white-space: pre-wrap">{{update.body}}</p>
                            </div>
                        </div>
                    </div>
                </div>
                {%endfor%}
                {%endif%}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>
{%endif%}
{% endblock %}

projects/templates/projects/project_request.html
{% extends "base.html" %}
{% load static %} 


{% block content %} 
<div class="overlay"></div>
<div class="container-fluid">
    <div class="row">
        <div class="col-10 offset-1 ">
            <div class="row">
                <div class="col comments" style="padding: 10px;">
                    <div class="card h-10 border-0">
                        <h5 class="card-title">
                            Suggest a new Project for me!
                        </h5>
                        {% load crispy_forms_tags %}
                        <div class="card-body pb-3">
                            <form method="post" style="margin-top: 1.3em;" enctype="multipart/form-data">
                                {{ project_form | crispy }}
                                <!-- calculate a price based on category + timescale-->

                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary btn-lg" name="action" value="submit">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
                <hr>
            </div>
        </div>
        
    </div>

</div>
{% endblock %}
{% block postloadjs %} 
{{block.super}}
<script type = "text/javascript">
    function update() {
        var scale = $('#id_scale').val()
        var category = $('#id_category option:selected').val()
        price = {{costDistribution|safe}}[scale + category]
        if (!price) {
            price = "n/a"
        }
        else {
            price = "£" + price.toFixed(2);
        }
        $('#id_priceEstimate').val(price)
    }
    $('#id_scale').change(update)
    $('#id_category').change(update)
    update()
</script>
{% endblock %}

projects/templates/projects/projects.html
{% extends "base.html" %}
{% load static %} 


{% block content %} 
<div class="overlay"></div>
<div class="container-fluid">
    <div class="row">
        <div class="col text-center mt-3">
            <h2 class="logo-font">My past projects</h2>
            {% for category in categories %}
                <a class="text-muted" href="{%url 'projects'%}?category={{category.name}}">
                    {{category.friendly_name}}
                </a>
                {% if not forloop.last %}|{% endif %}
            {% endfor %}
            {% if request.user.is_superuser %}
                <div class="text-center">
                    <a class="btn btn-info float-center" href="{% url 'add_project' %}" role="button">Add item</a>
                </div>
                
            {% endif %}
            <hr class="w-50 mb-1">
        </div>
    </div>
    <div class="row">
        <div class="project-container col-10 offset-1">
            <div class="row mt-1 mb-2">
                <div class="col-12 col-md-6 order-md-last d-flex justify-content-center justify-content-md-end">
                    <select id="sort-selector" class="border-{%if sorting != 'None_None'%}info{%else%}black{%endif%} rounded">
                        {% for possibleSorting in possibleSortings %}
                            <option value="{{possibleSorting.name}}" {%if sorting == possibleSorting.name%}selected{%endif%}>{{possibleSorting.friendlyName}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-12 col-md-6 order-md-first">
                    <p class="text-muted mt-3 text-center text-md-left">
                        {{projects|length}} Projects {%if search%} found for <strong>"{{search}}"</strong> {%endif%}
                    </p>
                </div>
            </div>
            <div class="row">
                {% load timedelta_filter %}
                {% for project in projects %}
                    <div class="col-sm-6 col-md-6 col-lg-3">
                        <div class="card h-100 border-0">
                            <a href="{% url 'project_details' project.id %}">
                                <img class="card-img-top img-fluid" src="{% if project.image %}{{project.image.url}}{%else%}{{ MEDIA_URL}}/noimage.png{%endif%}" alt="{{project.name}}">
                            </a>
                            <div class="card-body pb-0">
                                <p class="mb-0"><strong>{{ project.name }}</strong></p>
                            </div>
                            <div class="card-footer bg-white pt-0 bnorder-0 text-left">
                                <div class="row">
                                    <div class="col">
                                        {% if project.category %} 
                                        <a class="text-muted" href="{%url 'projects'%}?category={{project.category.name}}">
                                            {{project.category.friendly_name}}
                                        </a>
                                        {% endif %}
                                        <p class="lead mb-0 text-left">
                                        {% if project.startDate %} 
                                            {{project.startDate}} - {{project.endDate}}
                                        {% else %}
                                            Project expected to take {{project.expectedLength|timedelta:"{days_total} day(s)"}}
                                        {% endif %}
                                        </p>

                                        {% if project.price %}
                                            <p class="lead mb-0 text-left">Cost : £{{project.price}}</p>
                                        {% endif %}
                                        <hr>
                                        {% if project.approved %}
                                            {% if project.commission %} 
                                                <p>funded by {{project.commission.user}}</p>
                                            {% elif request.user.is_authenticated %}
                                                <div class="text-center">
                                                    <a class="btn btn-primary float-center" href="{%url 'checkout' project.id%}" role="button">Fund this project for £{{project.price}}!</a>
                                                </div>
                                            {% else %}
                                                <div class="text-center">
                                                    <a class="btn btn-info float-center" href="#" role="button">Please log in if you want to fund this item!</a>
                                                </div>
                                            {%endif%}
                                        {%else%}
                                            <div class="text-center">
                                                <a class="btn btn-danger float-center" href="{% url 'project_details' project.id %}" role="button">Project not yet approved</a>
                                            </div>
                                        {%endif%}
                                        {% if request.user.is_superuser %}
                                            <br>
                                            <small class="ml-3">
                                                <a href="{% url 'edit_project' project.id %}">Edit</a> | 
                                                <a class="text-danger" href="{% url 'delete_project' project.id %}">Delete</a>
                                            </small>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% if forloop.counter|divisibleby:1%}
                    <div class="col-12 d-sm-none">
                        <hr>
                    </div>
                    {%endif%}
                    {% if forloop.counter|divisibleby:2%}
                    <div class="col-12 d-none d-sm-block d-md-block d-lg-none">
                        <hr>
                    </div>
                    {%endif%}
                    
                    {% if forloop.counter|divisibleby:4%}
                    <div class="col-12 d-none d-lg-block d-xl-block">
                        <hr>
                    </div>
                    {%endif%}

                    
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %} 
{{block.super}}
<script type = "text/javascript">
    $('#sort-selector').change(function() {
        var selector = $(this)
        var currentUrl = new URL(window.location);

        var selectedVal = selector.val()
        if(selectedVal != "reset") {
            var sort = selectedVal.split("_")[0]
            var dir = selectedVal.split("_")[1]

            currentUrl.searchParams.set("sort", sort)
            currentUrl.searchParams.set("direction", dir)
        } else {
            currentUrl.searchParams.delete("sort")
            currentUrl.searchParams.delete("direction")
        }
        window.location.replace(currentUrl)
    })
</script>
{% endblock %}